click: click>=8.3,<8.5
commitizen: commitizen>=4.13,<5
coverage: coverage>=7.13,<8
fastapi: fastapi>=0.135,<0.136
flask: flask>=3.1,<4
httpx2: httpx2>=2.12,<3
hatchling: hatchling>=1.28,<2
import-linter: import-linter>=2.9,<3
mypy: mypy>=1.19,<2
pip-audit: pip-audit>=2.10,<3
pre-commit: pre-commit>=4.5,<5
pydantic: pydantic>=2.12,<3
pyright: pyright>=1.1,<2
pytest: pytest>=9.0,<10
pytest-cov: pytest-cov>=7.0,<8
pylint: pylint>=4.0,<5
ruff: ruff>=0.16,<0.17
setuptools: setuptools>=80,<81
structlog: structlog>=25.5,<26
ty: ty>=0.0.75,<0.1
typer: typer>=0.21,<0.22
uv-build: uv_build>=0.12,<0.13
uvicorn: uvicorn>=0.41,<0.42
